# Generated by Django 4.0.3 on 2022-08-04 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_adminuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='root_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PharmacyStaff',
            fields=[
                ('baseuseraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuseraccount')),
                ('account_number', models.IntegerField(null=True)),
                ('admin_token', models.CharField(max_length=200, null=True)),
            ],
            bases=('users.baseuseraccount',),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='baseuseraccount_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuseraccount'),
            preserve_default=False,
        ),
    ]
