# Generated by Django 4.0.3 on 2022-08-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash', models.IntegerField()),
                ('opening_stock', models.IntegerField()),
                ('opening_date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('closing_cash', models.IntegerField(null=True)),
                ('closing_stock', models.IntegerField(null=True)),
                ('closing_date', models.DateField(null=True, verbose_name='date')),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('book_date', models.DateField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('book_date', models.DateField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('balanced', models.BooleanField(default=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
    ]
