# Generated by Django 4.0.3 on 2022-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessmonth',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
