# Generated by Django 4.0.3 on 2024-01-11 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='book_date',
            field=models.DateField(default=datetime.date(2024, 1, 11), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='book_date',
            field=models.DateField(default=datetime.date(2024, 1, 11), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default=datetime.date(2024, 1, 11), verbose_name='date'),
        ),
    ]
