# Generated by Django 4.0.3 on 2024-01-11 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_credit_book_date_alter_debit_book_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessmonth',
            name='opening_date',
            field=models.DateField(default=datetime.date(2024, 1, 11), verbose_name='opening date'),
        ),
    ]
