# Generated by Django 4.0.3 on 2022-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_stock_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='drug',
            field=models.CharField(max_length=100),
        ),
    ]
