# Generated by Django 4.0.3 on 2022-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_stock_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
