# Generated by Django 4.0.3 on 2024-01-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bussinessmonth_opening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessmonth',
            name='opening_date',
            field=models.DateField(default='2024-01-11', verbose_name='opening date'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='book_date',
            field=models.DateField(default='2024-01-11', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='book_date',
            field=models.DateField(default='2024-01-11', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default='2024-01-11', verbose_name='date'),
        ),
    ]
