# Generated by Django 4.0.3 on 2022-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessmonth',
            name='closing_date',
            field=models.DateField(null=True, verbose_name='closing date'),
        ),
        migrations.AlterField(
            model_name='bussinessmonth',
            name='opening_date',
            field=models.DateField(auto_now_add=True, verbose_name='opening date'),
        ),
    ]
