# Generated by Django 4.0.3 on 2024-01-24 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bussinessmonth_opening_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessmonth',
            name='opening_date',
            field=models.DateField(default=datetime.date(2024, 1, 24), verbose_name='opening date'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='book_date',
            field=models.DateField(default='2024-01-24', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='book_date',
            field=models.DateField(default='2024-01-24', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default='2024-01-24', verbose_name='date'),
        ),
    ]
