# Generated by Django 4.0.3 on 2022-11-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('drug_type', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('Tab', 'Tab'), ('Suspension', 'Suspension'), ('Injectable', 'Injectable')], max_length=20)),
                ('weight', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=30)),
                ('exp_date', models.DateField(verbose_name='Expiery Date')),
                ('stock_amount', models.IntegerField()),
                ('purchase_amount', models.IntegerField()),
                ('units', models.CharField(choices=[('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Sachets', 'Sachets')], default='Packets', max_length=30)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=10)),
                ('day_added', models.DateField(auto_now_add=True)),
                ('out_of_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('tab_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_cd', models.CharField(max_length=10, null=True)),
                ('remainder', models.IntegerField(default=0, null=True)),
                ('no_packs', models.IntegerField(default=0, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('total_price', models.IntegerField(null=True)),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
    ]
