# Generated by Django 4.0.3 on 2022-11-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablet',
            old_name='tab_id',
            new_name='id',
        ),
    ]
