# Generated by Django 4.0.3 on 2022-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
