# Generated by Django 4.0.3 on 2024-01-11 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default=datetime.date(2024, 1, 11)),
        ),
    ]
