# Generated by Django 4.0.3 on 2022-08-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='expired',
        ),
    ]
