# Generated by Django 5.0.6 on 2024-07-01 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 44, 47, 928992, tzinfo=datetime.timezone.utc)),
        ),
    ]
