# Generated by Django 4.0.3 on 2022-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drug',
            name='exp_date',
            field=models.DateField(verbose_name='Expiery Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
