# Generated by Django 4.0.3 on 2022-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_remove_drug_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='state',
            field=models.CharField(choices=[('Tab', 'Tab'), ('Suspension', 'Suspension'), ('Injectable', 'Injectable')], default='Tab', max_length=20),
            preserve_default=False,
        ),
    ]
