# Generated by Django 4.0.3 on 2022-11-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_rename_tab_id_tablet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablet',
            name='remainder',
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bottles', models.IntegerField(null=True)),
                ('no_packs', models.IntegerField(default=0, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Injectable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bottles', models.IntegerField(null=True)),
                ('no_packs', models.IntegerField(default=0, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
    ]
