# Generated by Django 4.0.3 on 2022-12-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_remove_tablet_remainder_suspension_injectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='drug',
            name='state',
            field=models.CharField(choices=[('Tab', 'Tab'), ('Suspension', 'Suspension'), ('Injectable', 'Injectable')], default='Tab', max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='units',
            field=models.CharField(choices=[('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Unit', 'Sachets/Bottle/Card')], default='Packets', max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
