# Generated by Django 4.0.3 on 2022-07-28 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_out_of_stock_alter_drug_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='day_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
