# Generated by Django 4.0.3 on 2022-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='remainder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='tab_cd',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
