# Generated by Django 4.0.3 on 2022-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drug_remainder_drug_tab_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='remainder',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
