# Generated by Django 4.0.3 on 2022-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drug_day_added_drug_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
