# Generated by Django 4.0.3 on 2024-01-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_alter_drug_day_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default='2024-01-24'),
        ),
    ]
