# Generated by Django 4.0.3 on 2022-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_alter_drug_remainder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='price',
        ),
        migrations.AddField(
            model_name='drug',
            name='pack_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
