# Generated by Django 4.0.3 on 2022-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_remove_drug_price_drug_pack_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
