# Generated by Django 4.0.3 on 2024-03-24 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_alter_drug_day_added_alter_sale_sale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default='2024-03-24'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_time',
            field=models.DateTimeField(default=datetime.time(19, 22, 48, 34814)),
        ),
    ]
