# Generated by Django 4.0.3 on 2022-11-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_drug_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_',
            fields=[
                ('drug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drugs.drug')),
                ('units', models.CharField(choices=[('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Sachets', 'Sachets')], max_length=30)),
            ],
            bases=('drugs.drug',),
        ),
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(auto_now_add=True, default="2022-11-11"),
            preserve_default=False,
        ),
    ]
