# Generated by Django 4.0.3 on 2022-11-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_drug__alter_drug_day_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug_',
        ),
    ]
