# Generated by Django 5.0.6 on 2024-06-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_remove_tablet_remainder_suspension_injectable'),
        ('drugs', '0008_alter_drug_day_added_alter_sale_sale_time'),
    ]

    operations = [
    ]
