# Generated by Django 4.0.3 on 2022-11-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_delete_drug_'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDrug',
            fields=[
                ('drug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drugs.drug')),
                ('units_', models.CharField(choices=[('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Sachets', 'Sachets')], max_length=30)),
            ],
            bases=('drugs.drug',),
        ),
    ]
