# Generated by Django 4.0.3 on 2022-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_subdrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pack_price',
        ),
        migrations.AddField(
            model_name='drug',
            name='no_packs',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
