# Generated by Django 4.0.3 on 2022-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_remove_drug_pack_price_drug_no_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='units',
            field=models.CharField(choices=[('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Sachets', 'Sachets')], default='Packets', max_length=30),
        ),
        migrations.AlterField(
            model_name='drug',
            name='no_packs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='SubDrug',
        ),
    ]
