# Generated by Django 4.0.3 on 2022-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_drug_units_alter_drug_no_packs_delete_subdrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
