# Generated by Django 4.0.3 on 2022-11-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_drug_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='purchase_amount',
            field=models.IntegerField(max_length=30),
        ),
    ]
